#PG
#host: 'localhost'
#adapter: 'postgresql'
#database: 'linael'
#username: 'linael' 
#password: 'password'

#SQLITE
linael:
  adapter: sqlite3
  database: db/linael.sqlite3
  pool: 20
  timeout: 5000
  encoding: 'utf8'
